skins.1=1
name.1=ipattern:*Default*

skins.2=2
name.2=ipattern:Pegasus1

skins.3=3
name.3=ipattern:Pegasus2

skins.4=4
name.4=ipattern:Pegasus3

skins.5=5
name.5=ipattern:*Thestral*

skins.2=2 3 4
name.2=iregex:.*(Pegasus|Alicorn).*

skins.8=1 2 3 4 5
weights.8=1 0 0 0 0