skins.1=1
name.1=ipattern:*Default*

skins.2=2
name.2=ipattern:*Wooly*

skins.3=3
name.3=ipattern:*Ashen*

skins.4=4
name.4=ipattern:*Cookie*

skins.5=6
name.5=ipattern:*Umbra*

skins.6=5
name.6=ipattern:*Albino*

skins.7=1 2 3 4 5 6
biomes.7=taiga windswept_hills
weights.7=100 8 8 8 1

skins.8=1 2 3 4 5 6
biomes.8=snowy_taiga windswept_gravely_hills frozen_river
weights.8=8 100 8 8 1 50

skins.9=1 2 3 4 5 6
biomes.9=old_growth_pine_taiga old_growth_spruce_taiga
weights.9=8 8 100 8 1 8

skins.10=1 2 3 4 5 6
biomes.10=windswept_forest
weights.10=8 8 8 100 1 8

skins.10=1 2 3 4 5 6
biomes.10=dappled_forest
weights.10=8 50 8 8 1 8 50

skins.12=1 2 3 4 5 6
weights.12=100 100 100 100 100 1
