skins.1=1
name.1=iregex:.*(tan|Default|(Dr|Doctor).*Trayaurus).*

skins.2=2
name.2=ipattern:*Black*

skins.3=3
name.3=ipattern:*Brown*

skins.4=4
name.4=ipattern:*white*

skins.5=5
name.5=ipattern:*vitiligo*

skins.6=6
name.6=ipattern:*Villager*#4*

skins.7=1
weights.7=1