skins.1=4
name.1=ipattern:*storage*cube*
blocks.1=tripwire oak_pressure_plate spruce_pressure_plate birch_pressure_plate jungle_pressure_plate acacia_pressure_plate dark_oak_pressure_plate mangrove_pressure_plate cherry_pressure_plate pale_oak_pressure_plate bamboo_pressure_plate crimson_pressure_plate warped_pressure_plate stone_pressure_plate polished_blackstone_pressure_plate heavy_weighted_pressure_plate light_weighted_pressure_plate

skins.2=5
name.2=ipattern:*companion*cube*
blocks.2=tripwire oak_pressure_plate spruce_pressure_plate birch_pressure_plate jungle_pressure_plate acacia_pressure_plate dark_oak_pressure_plate mangrove_pressure_plate cherry_pressure_plate pale_oak_pressure_plate bamboo_pressure_plate crimson_pressure_plate warped_pressure_plate stone_pressure_plate polished_blackstone_pressure_plate heavy_weighted_pressure_plate light_weighted_pressure_plate

skins.3=1
name.3=ipattern:*storage*cube*

skins.4=2
name.4=ipattern:*companion*cube*

skins.5=3
name.5=ipattern:*vintage*cube*