skins.1=1
name.1=ipattern:*Default*

skins.2=2
name.2=ipattern:*Soul Skeleton*
usingShaders.2=false

skins.3=8
name.3=ipattern:*Soul Skeleton*
usingShaders.3=true

skins.4=3
name.4=ipattern:*Mossy Skeleton*

skins.5=4
name.5=ipattern:*Bubble Coral Sunken Skeleton*

skins.6=5
name.6=ipattern:*Fire Coral Sunken Skeleton*

skins.7=6
name.7=ipattern:*Horn Coral Sunken Skeleton*

skins.8=4 5 6
name.8=ipattern:*Sunken Skeleton*

skins.9=7
name.9=ipattern:*dungeon*

skins.10=1 2 3 4 5 6 7
weights.10=0 0 1 0 0 0 0
biomes.10=Jungle Sparse_Jungle Bamboo_Jungle Lush_Caves

skins.11=8
biomes.11=Soul_Sand_Valley
usingShaders.11=true


skins.12=1 2 3 4 5 6 7
weights.12=0 1 0 0 0 0 0
biomes.12=Soul_Sand_Valley
usingShaders.12=false

skins.13=1 2 3 4 5 6 7
weights.13=0 0 0 4 1 1 0
biomes.13=River Frozen_River Warm_Ocean Lukewarm_Ocean Deep_Lukewarm_Ocean Ocean Deep_Ocean Cold_Ocean Deep_Cold_Ocean Frozen_Ocean Deep_Frozen_Ocean
heights.13=-64-63

skins.14=1 2 3 4 5 6 7
weights.14=3 0 0 4 1 1 3
biomes.14=Stony_Shore Beach
heights.14=-64-70

skins.15=1 7
weights.15=1 1