skins.1=1
name.1=iregex:.*(default|shaven|villager.*#4|(Doctor|Dr).*Trayaurus).*

skins.2=3
name.2=ipattern:*horseshoe*

skins.3=4
name.3=ipattern:*goatee*moustache*

skins.4=11
name.4=ipattern:*long*beard*

skins.5=14
name.5=ipattern:*mutton*chops*moustache*

skins.6=10
name.6=ipattern:*chin*strap*moustache*

skins.7=8
name.7=ipattern:*handlebar*

skins.8=9
name.8=ipattern:*goatee*

skins.9=7
name.9=ipattern:*chin*strap*

skins.10=5
name.10=ipattern:*beard*

skins.11=12
name.11=ipattern:*fu*manchu*

skins.12=13
name.12=ipattern:*robotnik*

skins.13=6
name.13=iregex:.*(mutton.*chops|Schlatt).*

skins.14=2
name.14=ipattern:*moustache*

skins.15=15
name.15=ipattern:*idkman*

skins.16=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
weights.16=219 1 1 1 1 1 1 1 1 1 1 1 1 1 1