skins.1=6
name.1=ipattern:*Common*

skins.2=2
name.2=iregex:(.*Orca.*|Willy|Shamu)

skins.3=3
name.3=iregex:(.*Amazon River Dolphin.*|Boto)

skins.4=4
name.4=ipattern:*Beluga*

skins.5=5
name.5=ipattern:*Narwhal*

skins.6=1
name.6=ipattern:*Dolphin*