skins.1=1
name.1=ipattern:*Default*


skins.2=2
name.2=ipattern:*Bone*
usingShaders.2=false


skins.3=8
name.3=ipattern:*Bone*
usingShaders.3=true

skins.4=4
name.4=ipattern:*Glowing*Scorpion*
usingShaders.4=false

skins.5=7
name.5=ipattern:*Glowing*Scorpion*
usingShaders.5=true


skins.6=5
name.6=ipattern:*Black*Scorpion*


skins.7=3
name.7=ipattern:*Scorpion*


skins.8=6
name.8=ipattern:*Black*Widow*


skins.9=1 2 3 4 5 6
weights.9=0 0 0 1 0 0
biomes.9=wooded_badlands desert desert_hills desert_lakes badlands badlands_plateau modified_badlands_plateau wooded_badlands_plateau modified_wooded_badlands_plateau eroded_badlands
heights.9=0-55
usingShaders.9=false


skins.10=1 2 3 7 5 6
weights.10=0 0 0 1 0 0
biomes.10=wooded_badlands desert desert_hills desert_lakes badlands badlands_plateau modified_badlands_plateau wooded_badlands_plateau modified_wooded_badlands_plateau eroded_badlands
heights.10=0-55
usingShaders.10=true

skins.11=1 2 3 4 5 6
weights.11=0 0 2 0 1 0
biomes.11=wooded_badlands desert desert_hills desert_lakes badlands badlands_plateau modified_badlands_plateau wooded_badlands_plateau modified_wooded_badlands_plateau eroded_badlands
heights.11=56-256


skins.12=1 2 6
weights.12=10 5 5
heights.12=-64-0
usingShaders.12=false

skins.13=1 8 6
weights.13=10 5 5
heights.13=-64-0
usingShaders.13=true


skins.14=1 6
weights.14=2 1