skins.1=1
name.1=iregex:.*(default|unscarred|villager.*#4|(Doctor|Dr).*Trayaurus).*

skins.2=3
name.2=iregex:.*right.*eye.*patch.*

skins.3=2
name.3=iregex:.*eye.*patch.*

skins.4=4
name.4=iregex:.*right.*eye.*burn.*

skins.5=5
name.5=iregex:.*eye.*burn.*

skins.6=6
name.6=iregex:.*left.*eye.*slash.*

skins.7=7
name.7=iregex:.*eye.*slash.*

skins.8=8
name.8=iregex:.*(joker|smile).*

skins.16=1 2 3 4 5 6 7 8
weights.16=150 5 5 1 1 4 4 0