skins.1=1
name.1=ipattern:*default*

skins.2=21
name.2=ipattern:*pale*moss*

skins.3=15
name.3=ipattern:*pale*

skins.4=8
name.4=ipattern:*dark*

skins.5=3
name.5=ipattern:*swamp*

skins.6=22
name.6=ipattern:*badlands*

skins.7=4
name.7=ipattern:*birch*

skins.8=6
name.8=ipattern:*snow*

skins.9=5
name.9=ipattern:*spruce*

skins.10=7
name.10=ipattern:*jungle*

skins.11=9
name.11=ipattern:*acacia*

skins.12=11
name.12=ipattern:*flowering*azalea*

skins.13=10
name.13=ipattern:*azalea*

skins.14=20
name.14=ipattern:*root*

skins.15=12
name.15=ipattern:*mangrove*

skins.16=13
name.16=ipattern:*cherry*

skins.17=17
name.17=ipattern:*cactus*flower*

skins.18=16
name.18=ipattern:*cactus*

skins.19=18
name.19=ipattern:*moss*

skins.20=19
name.20=ipattern:*lichen*

skins.21=2
name.21=ipattern:*Oak*

skins.22=23
name.22=ipattern:*red*poplar*

skins.23=24
name.23=ipattern:*orange*poplar*

skins.24=25
name.24=ipattern:*yellow*poplar*

skins.25=23 24 25
name.25=ipattern:*poplar*

skins.26=26
name.26=ipattern:*dungeons*

skins.27=1
weights.27=1