skins.1=1
name.1=ipattern:*default*

skins.2=21
name.2=ipattern:*pale*moss*

skins.3=15
name.3=ipattern:*pale*

skins.4=8
name.4=ipattern:*dark*

skins.5=3
name.5=ipattern:*swamp*

skins.6=22
name.6=ipattern:*badlands*

skins.7=4
name.7=ipattern:*birch*

skins.8=6
name.8=ipattern:*snow*

skins.9=5
name.9=ipattern:*spruce*

skins.10=7
name.10=ipattern:*jungle*

skins.11=9
name.11=ipattern:*acacia*

skins.12=11
name.12=ipattern:*flowering*azalea*

skins.13=10
name.13=ipattern:*azalea*

skins.14=20
name.14=ipattern:*root*

skins.15=12
name.15=ipattern:*mangrove*

skins.16=13
name.16=ipattern:*cherry*

skins.17=17
name.17=ipattern:*cactus*flower*

skins.18=16
name.18=ipattern:*cactus*

skins.19=18
name.19=ipattern:*moss*

skins.20=19
name.20=ipattern:*lichen*

skins.21=2
name.21=ipattern:*Oak*

skins.22=23
name.22=ipattern:*red*poplar*

skins.23=24
name.23=ipattern:*orange*poplar*

skins.24=25
name.24=ipattern:*yellow*poplar*

skins.25=23 24 25
name.25=ipattern:*poplar*

skins.26=1 10 11 18 19
biomes.26=lush_caves
weights.26=8 100 25 25 8

skins.27=1 19
heights.27=(-999)-50
weights.27=25 100

skins.28=1 2 4
biomes.28= forest meadow river 
weights.28=8 100 25

skins.29=1 2
biomes.29=beach plains stony_peaks stony_shore sunflower_plains  
weights.29=8 100

skins.30=1 4
biomes.30=birch_forest old_growth_birch_forest
weights.30=8 100

skins.31=1 4 8
biomes.31=dark_forest
weights.31=8 8 100

skins.32=1 3
biomes.32=swamp
weights.32=8 100

skins.33=1 6
biomes.33=frozen_peaks jagged_peaks snowy_beach snowy_slopes frozen_ocean ice_spikes frozen_river
weights.33=8 100

skins.34=1 5
biomes.34=old_growth_spruce_taiga old_growth_pine_taiga taiga
weights.34=8 100

skins.35=1 5 6
biomes.35=grove snowy_taiga snowy_plains
weights.35=8 25 100

skins.36=1 2 5
biomes.36=windswept_forest windswept_gravelly_hills windswept_hills
weights.36=8 0 100

skins.37=1 7
biomes.37=bamboo_jungle
weights.37=8 100

skins.38=1 2 7
biomes.38=jungle sparse_jungle
weights.38=8 25 100

skins.39=1 9
biomes.39=savanna_plateau savanna windswept_savanna
weights.39=8 100

skins.40=1 12 20
biomes.40=mangrove_swamp
weights.40=8 100 25

skins.41=1 13
biomes.41=cherry_grove
weights.41=8 100

skins.42=1 15 21
biomes.42=pale_garden
weights.42=8 100 50

skins.43=1 22
biomes.43=wooded_badlands
heights.43=(75)-999
weights.43=8 100

skins.44=1 16 17
biomes.44=desert badlands eroded_badlands wooded_badlands
weights.44=8 100 25

skins.45=1 23 24 25 5
biomes.45=dappled_forest
weights.45=8 200 240 90 27

skins.45=1 2
weights=8 100
