skins.4=1
name.4=ipattern:*Default*

skins.5=2
name.5=iregex:(Brian, Sales Associate|Brian|.*Dried Muddy.*)

skins.6=3
name.6=ipattern:*Piebald*

skins.7=4
name.7=ipattern:*Spotted*

skins.8=5
name.8=ipattern:*technoblade*

skins.9=1 2 3 4
biomes.9=plains forest dark_forest cherry_grove
weights.9=100 25 8 8

skins.10=1 2 3 4
biomes.10=sunflower_plains flower_forest
weights.10=8 4 100 8

skins.11=1 2 3 4
biomes.11=birch_forest old_growth_birch_forest
weights.11=8 4 8 100

skins.13=1 2 3 4
weight.13=1 1 1 1