skins.1=1
name.1=iregex:.*(default|unscarred|villager.*#4|(Doctor|Dr).*Trayaurus).*

skins.2=3
name.2=iregex:.*right.*eye.*patch.*

skins.3=2
name.3=iregex:.*eye.*patch.*

skins.4=4
name.4=ipattern:*glasses*

skins.5=1
weights.5=1