skins.1=1
name.1=iregex:.*(unscarred|default|villager.*#4|(Doctor|Dr).*Trayaurus|Schlatt).*

skins.2=2
name.2=iregex:.*right.*eye.*burn.*

skins.3=3
name.3=iregex:.*eye.*burn.*

skins.4=4
name.4=iregex:.*left.*eye.*slash.*

skins.5=5
name.5=iregex:.*eye.*slash.*

skins.6=6
name.6=iregex:.*(joker|smile|glasgow).*

skins.7=7
name.7=iregex:.*big.*boss.*

skins.8=1
weights.8=1