skins.1=1
name.1=iregex:.*(default|unscarred|villager.*#4|(Doctor|Dr).*Trayaurus).*

skins.2=2
name.2=iregex:.*right.*eye.*burn.*

skins.3=3
name.3=iregex:.*eye.*burn.*

skins.4=4
name.4=iregex:.*left.*eye.*slash.*

skins.5=5
name.5=iregex:.*eye.*slash.*

skins.6=6
name.6=iregex:.*(joker|smile).*

skins.7=1 2 3 4 5 6 
weights.7=150 1 1 4 4 0