textures.2=2
name.2=iregex:.*wild-tailed.*

textures.3=3
name.3=iregex:.*gold-tailed.*

textures.4=4
name.4=iregex:.*cyan-tailed.*

textures.5=5
name.5=iregex:.*black-tailed.*

textures.6=6
name.6=iregex:.*green-tailed.*

textures.7=7
name.7=iregex:.*blue-tailed.*

textures.8=8
name.8=iregex:.*albino-tailed.*

textures.9=9
name.9=iregex:.*lucy-tailed.*

textures.10=1