textures.1=1
name.1=ipattern:*default*

textures.2=3
name.2=iregex:.*green.*chimera.*

textures.3=4
name.3=iregex:.*albino.*chimera.*

textures.4=5
name.4=iregex:.*blue.*chimera.*

textures.5=6
name.5=iregex:.*cyan.*chimera.*

textures.6=7
name.6=iregex:.*gold.*chimera.*

textures.7=8
name.7=iregex:.*lucy.*chimera.*

textures.8=9
name.8=iregex:.*wild.*chimera.*

textures.9=2
name.9=iregex:.*chimera.*

textures.10=1 2 3 4 5 6 7 8 9
weights.10=100 1 1 1 1 1 1 1 1